### ISSUE TITLE
提示网络错误

### ISSUE THREAD

**Issue by uyqf** [Loopring/dexwebapp#1]
Brave浏览器 版本 1.3.118 Chromium: 80.0.3987.116（正式版本） （64 位）
MetaMask 版本 7.7.0.1

登录网址后，提示网络错误，切换以太坊网络到测试网络，然后再切换回来，正常，创建账号，输入密码后提交，狐狸头无法弹出创建账号请求。
如果意见被采纳，请将奖励发至：0x0e07e4047442d8ae3b50f9b1335c35a86192a1da
万分感谢！

**Comment by dong77** [comment]
我们会替换掉直接和MetaMask的集成，所有相关问题都会通过和onboard.js的集成获得解决。目前相关的问题的确很多。
