### ISSUE TITLE
右侧slider优化建议

### ISSUE THREAD

**Issue by tianheng2017** [Loopring/dexwebapp#10]
感觉右侧slider 应该是这样：鼠标移动到用户账号上面弹出slider，鼠标离开slider区域后收缩slider

**Comment by tianheng2017** [comment]
充值页面细节：默认资产ETH，当选择其他资产后，应有一个loading图层，直到以太坊上余额刷新后再销毁loading图层

**Comment by tianheng2017** [comment]
订单薄+买入卖出区域+最新成交区域  滚动条优化，当前是“原生滚动条”，又宽又亮在深色背景的衬托下更是刺眼，建议优化，参考okex“交易对区域”和“深度区域”的那种细小滚动条

**Comment by tianheng2017** [comment]
“您已经登陆。希望您喜欢路印安全高效的去中心化交易体验！”，在slider占用了3行，最后一行只有一个字，特别让人抓狂，精简下呗

**Comment by tianheng2017** [comment]
充值问题：充值已失败三次，转账hash分别为：https://etherscan.io/tx/0x527a1b55ab286ad544b939d3353dcb2ba4618cba6dc9b5c0d9f85015c48fd201
https://etherscan.io/tx/0xade90a2183a321aa5292ae59c5158bce88a4a9e1243b26dfb838435252e78e1a
https://etherscan.io/tx/0xc8257af6ec894cf981647cb4b8b13d55d47b8a46bb20e9d3b530ef80373e3a3e

**Comment by tianheng2017** [comment]
有效订单、历史订单、成交记录、充值记录、提现记录也缺少loading图层，网络不好话打开就是空白的以为系统有问题呢，实际上过很久条目会出来

**Comment by tianheng2017** [comment]
按照币圈常规买入应该是绿色色调，卖出为红色色调吧，目前反过来还有点不适应

**Comment by tianheng2017** [comment]
硬核建议：右侧我的以太地址->在Etherscan上打开按钮弹出的  https://etherscan.io/已经被墙了，严重影响体验，包括充值提现记录那部分也是这样，建议像IMtoken一样使用：https://cn.etherscan.com吧，

**Comment by tianheng2017** [comment]
订单薄：显示价格和数量2个字段就行了，如果能开发横向的柱状深度图做背景那就更好了

**Comment by tianheng2017** [comment]
充值页面，4条记录也出现了滚动条

**Comment by tianheng2017** [comment]
充值和提现的弹窗页面，标题部分用底色标识下，比如申请提现的背景为红色，申请充值的背景为绿色

**Comment by tianheng2017** [comment]
充值提现弹窗页面，选择数量部分应该增加一个全部按钮，不是没个人都能知道点击余额就能自动填充的

**Comment by tianheng2017** [comment]
IE11打不开，控制台提示“对象不支持“fill”属性或方法”，页面显示蓝色背景什么也没有，Chromium内核的浏览器可以，webpack应该是可以做兼容的啊

**Comment by tianheng2017** [comment]
最新成交价换算的USD最好能精确到小数点后4位

**Comment by tianheng2017** [comment]
页面色彩还需要调整，特别是框的渐变部分，看久了感觉视觉疲劳很累，喜欢okex那种简单的几种色彩

**Comment by tianheng2017** [comment]
交易图下面的一个区域，有效订单没有padding-left，建议和买卖对齐吧

**Comment by xiaowheat** [comment]
@tianheng2017 请把反馈写为多个issues

**Comment by dong77** [comment]
其实我们最初的实现就是上面那种。后来用户反馈slider搜索的太快了，才改的这个方式。

我倒是觉得我们可以改回去之前的样子，在听听其他用户的反馈。

**Comment by dong77** [comment]
下个版本尝试一下！
