### ISSUE TITLE
关于增加交易深度的问题

### ISSUE THREAD

**Issue by aBovine** [Loopring/dexwebapp#100]
为增订单深度，设定一个奖励池（挂单、交易、邀请奖励池）
1.挂单奖励：买一、买二，卖一、卖二的委托单超过10分钟的按照挂单数量比例奖励lrc代币，无需逐次发放，每天发放一次。

2.交易量奖励：交易量排名20-30的用户平均奖励奖池的20%，交易量排名10-20的名的用户的人平均奖励奖池的30%，交易量排名前10名的用户平均奖励奖池的50%。

3.邀请开户奖励：开户邀请码功能，邀请用户成功开户并交易10笔后，可奖励一定数量的lrc。

4.用户可自由选择提现速度，需即时提现的用户可以自由设置gas，默认可以由交易所批量处理提现手续最低。以后随着交易量的增，提现批处理的时间请适当缩短。

接收奖励地址：0x55db43ae45f7a73c6d2842712d7856a356b7e242

**Comment by xiaowheat** [comment]
https://blogs.loopring.org 会发布奖励计划
