### ISSUE TITLE
Flash crash? Plus minor suggestion

### ISSUE THREAD

**Issue by Pnin1204** [Loopring/dexwebapp#101]
On the 5th, there was a flash crash.  I've asked in chat, and can't seem to find any conversation on the topic.  I'm curious what caused it as I doubt it's anything but maybe a fat finger trade.  Just in case, it should be addressed.

But that brought up a suggestion I had. I know this is debatable, but as a user it would be convenient to see each trade's final total on both buy and sell side.  ie, with the flash crash, one of my orders filled at a reasonable price (wish I'd put it at 3 USD based on the charts).  I only had to multiply the ETH to the price to remember how much DAI I had put into the order, but it would have been nice to just see how much total DAI was spent in the order without running that calculation.  

At the very least, having everything show in a downloadable CSV for easy records, or having it visible in the orders rather than the trading window, would have been appreciated.  CSV export, btw, would be very useful in general, so that's really my biggest suggestion.

**Comment by dong77** [comment]
The "total" columns will be added soon, there is already an issue for that.

We also know there is some issue that can cause the web app to stop responding. We are still trying to find the cause.
