### ISSUE TITLE
Open Orders did not populate

### ISSUE THREAD

**Issue by Pnin1204** [Loopring/dexwebapp#102]
I wasn't able to record when it first happened, but after logging in, I put in an order, and it failed to display in the open orders section.  That's when I started the video recording, and that's the gif I'm uploading.  Unfortunately, I'm not able to reproduce it again, but I do demonstrate that it is happening in the gif. It wasn't until I changed the trading pair that I could see the open order as it should be.
![LoopringOpenOrderBug](https://user-images.githubusercontent.com/35647557/76150608-31186d00-6061-11ea-93dc-d9a2f869afe6.gif)

**Comment by dong77** [comment]
Submitting an order will have to go through the server for verification of signature before it's displayed in the open order table.

**Comment by xiaowheat** [comment]
Closed. It's not reproduced in the latest version of Loopring.io. Thanks.
