### ISSUE TITLE
Setting the browser zoom higher than 100% can cause large gaps in the order book

### ISSUE THREAD

**Issue by timet7** [Loopring/dexwebapp#103]
Setting the browser zoom higher than 100% (try 140%) can cause large gaps in the order book.

For example on the LINK/ETH pair the top of the order book can show up to several pages of blank space.

I'm not exactly sure what causes it but it will usually happen within a couple of minutes. 

What I did:
1. Go to the Link/ETH pair.
2. Change my browser zoom setting from 100% to 140%.
3. Scroll up and down the order book.
4. Change to a different trading pair then come back to Link/ETH.
5. Scroll to the top of the order book.

You should see it start populating blank space like shown in the attached picture.

Edit: Using the Brave browser.
![orderbook](https://user-images.githubusercontent.com/56006460/76167862-7b681f80-612f-11ea-8a04-51c14b660f3f.png)

Hope that helps!

0x38aC7EA6d2EDFf2d78E5af31B4caF27592b4e094

**Comment by xiaowheat** [comment]
@timet7 Could you point out where blank space is in the screenshot?

**Comment by timet7** [comment]
The whole screenshot shows blank space. When scrolling up or down the order book you'll see it gradually fill with space like shown in the screenshot which lacks any orders. Sorry, it's a bit difficult to explain.

It's really only noticeable at high zoom settings in the browser and doesn't appear when using the default 100% setting.

**Comment by dong77** [comment]
The orderbook is scrollable, you happened to scroll it to display placeholder '-'s.

**Comment by timet7** [comment]
> The orderbook is scrollable, you happened to scroll it to display placeholder '-'s.

Alright, that makes sense. I just thought at larger zoom settings it seemed kind of excessive. Sorry to waste your time.

The exchange is fantastic and IMO a real game changer in the DEX space. So keep doing what you're doing!
