### ISSUE TITLE
Can you erase this bad price on LINK - ETH pair? It is breaking graph + price 0.5 never been in history of LINK

### ISSUE THREAD

**Issue by lamart1** [Loopring/dexwebapp#105]
![linki](https://user-images.githubusercontent.com/10207118/76400206-34249d80-6380-11ea-9c18-a0b2b4f7e8b5.png)

**Comment by xiaowheat** [comment]
It's not a bad price. They are real trades

**Comment by lamart1** [comment]
> 
> 
> It's not a bad price. They are real trades

OK. I understand but it is making very bad UX
