### ISSUE TITLE
Chrome MetaMask插件未识别

### ISSUE THREAD

**Issue by enuoCM** [Loopring/dexwebapp#106]
问题描述:
  Chrome 原来已安装MetaMask，其他网站都可以正常使用MetaMask。loopring.io始终提示未安装MetaMask

操作系统和浏览器:
MetaMask 4.7.4
Chrome 版本 55.0.2883.87 m
Win10 17134.1130

截图：
![loopring-metamask](https://user-images.githubusercontent.com/10812343/76443543-8a83f180-63fd-11ea-82cc-70aae4b7cbe6.png)

**Comment by xiaowheat** [comment]
这个需要升级chrome到最新版本。最新的版本是80。

我们很难保证旧版本的兼容性
