### ISSUE TITLE
登录状态异常的bug，无法登录

### ISSUE THREAD

**Issue by PocketPQ** [Loopring/dexwebapp#107]
![image](https://user-images.githubusercontent.com/61608713/76480262-3141af80-6449-11ea-9a6b-ae28d6e4188b.png)
最近经常这样，一边显示已经登陆，一边让注册账号，清除缓存，强制刷新都不行。我的广告拦截也关闭了的。
不能任何操作也看不到资产了。只能过一会儿再试试。
就好像metamask确认了，但是不弹出让输入dex密码的页面类似

**Comment by dong77** [comment]
你这个截图看来就是没有注册账号啊。你的地址方便告诉我们吗？

**Comment by xiaowheat** [comment]
@PocketPQ 是否能提供操作系统和浏览器版本？

**Comment by PocketPQ** [comment]
Google Chrome 已是最新版本
版本 80.0.3987.132（正式版本） （64 位

**Comment by xiaowheat** [comment]
已修复，近期版本未出现。
