### ISSUE TITLE
Deposit status

### ISSUE THREAD

**Issue by shomius** [Loopring/dexwebapp#109]
Hi guys,  great looking exchange beta.  I noticed when depositing that the status under account tab>deposits>status doesn't update the number of blocks confirmed.  I checked etherscan while waiting and it showed 14 confirmations where your status still shows 0/30.  It only updates when completed.  Not a big deal but why is it there if it doesn't update status while waiting?

Great job guys! looking to trying out the rollup exchange.

Shomius

**Comment by xiaowheat** [comment]
Fixed in loopring.io
