### ISSUE TITLE
下单成功之后依然提示余额不足

### ISSUE THREAD

**Issue by ccyours** [Loopring/dexwebapp#11]
前置条件：账户余额充足
买入300LRC，点击按钮“买入LRC”，按钮旁提示“交易所余额不足”，少有延迟之后，网页右上角提示下单成功，同时扣除余额
是否应该是“提示余额不足之后下单失败”或者不应该提示余额不足（因为已经下单成功）。

**Comment by dong77** [comment]
这个我们看一下， @xiaowheat

**Comment by xiaowheat** [comment]
在最新的loopring.io中，未能复现
