### ISSUE TITLE
its more nicer to make the whole content scrollable.

### ISSUE THREAD

**Issue by ruhaise** [Loopring/dexwebapp#113]
![image](https://user-images.githubusercontent.com/25627383/76693331-78a38800-6663-11ea-86b0-2a4e9bd4c445.png)

I was on this page and tried to scroll the content and it wasnt possible, then I realized that I had to hover over the content to scroll it, the scrolling is not applicable to the main content div. 

only applicable to this part.
![image](https://user-images.githubusercontent.com/25627383/76693379-1eef8d80-6664-11ea-8266-76dce8008678.png)

**Comment by ruhaise** [comment]
![image](https://user-images.githubusercontent.com/25627383/76693388-6118cf00-6664-11ea-84ac-cd570b6dc529.png)
 same applies for all content pages.

**Comment by dong77** [comment]
will do. This is a known issue :)

**Comment by xiaowheat** [comment]
Updated. Thanks.
