### ISSUE TITLE
Information about deposit transaction can be a bit more wide value.

### ISSUE THREAD

**Issue by ruhaise** [Loopring/dexwebapp#114]
I have deposited some eth and it is more than 45 mins and still, the deposit didn't appear on my trading account, I think to avoid confusion and panic it's better to give some more wide values to the customer. 

transaction: https://etherscan.io/tx/0x51eeb4e0ff57ac0578d645dacb653a3224b3222bb2a496cb42e3353de78f3685

**Comment by dong77** [comment]
@ruhaise are you talking about higher gas price to make your deposit tx confirm quicker? If so, you need to use MetaMask to change the value. The exchange app doesn't propose the gas price.

- Click on "Edit"
- Click on 'Advanced'
- Change the gas price and click on "Save"
<img width="435" alt="Screen Shot 2020-03-15 at 19 30 17" src="https://user-images.githubusercontent.com/1710087/76712940-74bf4680-66f3-11ea-9f73-42b8359451d1.png">
<img width="445" alt="Screen Shot 2020-03-15 at 19 30 30" src="https://user-images.githubusercontent.com/1710087/76712941-77ba3700-66f3-11ea-86ed-65bffc34bf33.png">

**Comment by ruhaise** [comment]
No i mean even after the transaction is successful its not shown in the
loopring account. So i believe the 45min max window can be a bit
misleading. I propose to increase it a bit to much more reliable value.

**Comment by dong77** [comment]
I see. Thank you for your advice. We will adjust the wording accordingly. 

> 在 2020年3月15日，19:38，ruhaise <notifications@github.com> 写道：
> 
> ﻿
> No i mean even after the transaction is successful its not shown in the
> loopring account. So i believe the 45min max window can be a bit
> misleading. I propose to increase it a bit to much more reliable value.
>

**Comment by dong77** [comment]
fixed. the new minor version will be released in a few hours.
