### ISSUE TITLE
交易不是实时更新BUG

### ISSUE THREAD

**Issue by loopring1992** [Loopring/dexwebapp#116]
交易挂单时这边不扣除 不实时更新
![BUG](https://user-images.githubusercontent.com/61611786/76867537-9d387380-68a0-11ea-9b37-1a92b709ddd4.png)
好事多磨
0x58d5045A91Cf2748471302EA3d25b57ED4e5a7fc

**Comment by loopring1992** [comment]
上一条邮件问题描述的字输入错了。发现的问题是在挂单交易时，上面余额比如有1000LRC在挂单出售300LRC时，上面的余额不实时显示还有剩余700LRC，必须要刷新才会显示，刚刚在交易时依然是这个样子没有得到改变，这样在交易过程中不知道自己的实时余额，望您审查去留意一下这个BUG，

**Comment by xiaowheat** [comment]
已修复
