### ISSUE TITLE
多次交易后，委托列表显示错乱，有些成交了的单子还显示着

### ISSUE THREAD

**Issue by dos2004** [Loopring/dexwebapp#117]
![image](https://user-images.githubusercontent.com/3014710/76923090-6e0c1b80-690d-11ea-880f-ae09b9797c7a.png)
见上图，是我多次交易后委托列表显示错乱，有些成交了的单子还显示着，当我刷新页面后就变成了下面这样：
![image](https://user-images.githubusercontent.com/3014710/76923194-baeff200-690d-11ea-883f-5198ee158003.png)
望修复该问题，谢谢：钱包地址：0x081F8414046432b3399B38E28F79E289bDf8b8B7

**Comment by dos2004** [comment]
问题应该出在委托列表没有实时刷新，成交了的单子仍然显示着，给用户千万错乱

**Comment by xiaowheat** [comment]
这个是由于websocket的连接，出现卡顿造成的。

**Comment by xiaowheat** [comment]
已修复
