### ISSUE TITLE
订单总额限制的提示bug

### ISSUE THREAD

**Issue by PocketPQ** [Loopring/dexwebapp#119]
![image](https://user-images.githubusercontent.com/61608713/77133022-7d6d9f00-6a9c-11ea-8d43-0da6e014a2a6.png)
应该是订单总额，写成了订单数量

0xD28dC62611C424c51a9d01C8b962Eb02EAae9b28

**Comment by xiaowheat** [comment]
经过内部讨论，这个建议没有被采纳。谢谢
