### ISSUE TITLE
充值页面细节建议

### ISSUE THREAD

**Issue by tianheng2017** [Loopring/dexwebapp#12]
充值页面细节：默认资产ETH，当选择其他资产后，应有一个loading图层，直到以太坊上余额刷新后再销毁loading图层

**Comment by dong77** [comment]
这个建议不错。其实适用于所有异步等待的UI更新。

**Comment by dong77** [comment]
给奖励，请给个ETH地址。

**Comment by tianheng2017** [comment]
> 给奖励，请给个ETH地址。

0xC11956A97cf08e1cB48AAB895dB05f7AbD2523aD
