### ISSUE TITLE
点击logo区域会重置交易对

### ISSUE THREAD

**Issue by tianheng2017** [Loopring/dexwebapp#121]
![image](https://user-images.githubusercontent.com/29515610/78090166-f6a1b600-73fb-11ea-8fe8-b012a6402d7a.png)

BUG，点击浏览器或地址栏刷新都不会初始化交易对，但是点击LOGO区域却会初始化，希望也能够进行记忆，防止失误买错！

**Comment by xiaowheat** [comment]
这个已经在loopring.io中实现。是一个小的改进。谢谢。
