### ISSUE TITLE
Recent Trades list is duplicating entries

### ISSUE THREAD

**Issue by ebirbe** [Loopring/dexwebapp#124]
If you are in a market and wait for new orders to get to the "Recent Trades" list you will see that they appear duplicated, with exact same time, amount and price:

![Selección_974](https://user-images.githubusercontent.com/442938/79769344-fcebc980-82f9-11ea-87b3-c1d343387c44.png)
 
I can see clearly it is a bug because when you go to another market, then come back to the first one, you will see that the duplicated entries desapear

![Selección_975](https://user-images.githubusercontent.com/442938/79769539-420ffb80-82fa-11ea-9170-65d781ba3c32.png)

But if you wait again for new trades, they come to the list with a duplicated too.

**Comment by xiaowheat** [comment]
Fixed. Thanks.
