### ISSUE TITLE
Recent Trades -> Price loads incorrect format for LRC-ETH

### ISSUE THREAD

**Issue by pierrrek** [Loopring/dexwebapp#127]
Hi

I found that when switching to LRC-ETH the price populated to the Price (ETH price) in the Buy/Sell section is in the incorrect format when that price is selected from "Recent Trades".

As an example, when the price I select in "Recent Trades" is 0.00016276 then Price is populated with "1.6276E-4".

However, any "Recent Trades" that appear after my switch to LRC-ETH is correct.

In the picture below the blue arrow shows when I switched...
1. The Recent Prices above my attempt at a dotted line populates Price correctly.
2. Those below my "line" (which were there when I switched to LRC-ETH) gives the problem.

![image](https://user-images.githubusercontent.com/64374649/80315830-66883e00-87fa-11ea-8295-7f52172c028d.png)

This happens consistently for ONLY LRC-ETH. All other pairs are fine.

Cheers,
Pierre

**Comment by xiaowheat** [comment]
Fixed. Thanks.
