### ISSUE TITLE
Fill History - All trades show even if you select a Market

### ISSUE THREAD

**Issue by pierrrek** [Loopring/dexwebapp#128]
Before I start I must say... Thank you for my beautiful intro to DEX. It's my first time using one and I love it.

So when you go to the Fill History
https://loopring.io/orders/trade-history
*ALL FILLED TRADES SHOW* regardless of whether you select "All Markets" or whether you choose a market.

It's fine on order-history.

See pic for example:
![image](https://user-images.githubusercontent.com/64374649/80316587-e6b0a280-87fe-11ea-8099-b9ad52eca93d.png)

Kind Regards,
Pierre

**Comment by pierrrek** [comment]
Sorry about the close and open. First time using github on my mobile

**Comment by xiaowheat** [comment]
Fixed. Thanks.
