### ISSUE TITLE
订单金额限制能否取消

### ISSUE THREAD

**Issue by tianheng2017** [Loopring/dexwebapp#129]
![image](https://user-images.githubusercontent.com/29515610/80325891-94f13200-8869-11ea-8014-04f735b7a7c9.png)
这种还是不太好，建议取消上限，有一种情况就是我看好某个币，想挂他个100倍的价格放那儿，几年后再看，说不定成交了呢

**Comment by xiaowheat** [comment]
经过内部讨论，这个建议没有被采纳。谢谢
