### ISSUE TITLE
页面多个滚动条造成的美观问题

### ISSUE THREAD

**Issue by tianheng2017** [Loopring/dexwebapp#13]
订单薄+买入卖出区域+最新成交区域 滚动条优化，当前是“原生滚动条”，又宽又亮在深色背景的衬托下更是刺眼，建议优化，参考okex“交易对区域”和“深度区域”的那种细小滚动条

**Comment by dong77** [comment]
已经修复。

**Comment by dong77** [comment]
给奖励。请把你的以太坊地址分享一下给我。

**Comment by tianheng2017** [comment]
0xC11956A97cf08e1cB48AAB895dB05f7AbD2523aD

**Comment by tianheng2017** [comment]
> 给奖励。请把你的以太坊地址分享一下给我。

0xC11956A97cf08e1cB48AAB895dB05f7AbD2523aD
