### ISSUE TITLE
BUG：屏幕宽度问题

### ISSUE THREAD

**Issue by tianheng2017** [Loopring/dexwebapp#130]
当屏幕宽度在1000px时，顶部价格栏会被折叠，但是在“明亮主题”下，折叠符号是白色的看不见，且折叠hover区域颜色也不对（应该从“暗黑主题”北京改成“明亮主题”背景），如图所示：
![image](https://user-images.githubusercontent.com/29515610/80326453-6d02ce00-886b-11ea-9fc2-b9ab4a37723f.png)

![image](https://user-images.githubusercontent.com/29515610/80326493-8e63ba00-886b-11ea-8d90-0043593ace93.png)

**Comment by xiaowheat** [comment]
这个已经修复。谢谢。
