### ISSUE TITLE
wallet connet问题

### ISSUE THREAD

**Issue by tianheng2017** [Loopring/dexwebapp#131]
谷歌浏览器打开交易所   ->   使用ios版trust扫码登录，开启自动签署交易   ->   随后按home键直接退出trust -> 关闭浏览器，在打开路印交易所，居然还可以交易，而且是免登录的。。。。。。如果忘记退出账号，会不会有安全问题呢

**Comment by xiaowheat** [comment]
在近期的升级后，没有这个问题了
