### ISSUE TITLE
反复刷新也获取不到数据的bug

### ISSUE THREAD

**Issue by tianheng2017** [Loopring/dexwebapp#133]
![image](https://user-images.githubusercontent.com/29515610/80441381-6cd30300-893d-11ea-90ab-4fcb76fbeaca.png)

没有任何数据，只有框框，已经反复刷新5次，且浏览器处于载入完毕状态

**Comment by xiaowheat** [comment]
这个和网络的状况有关。连不上，请查看翻墙的情况。
