### ISSUE TITLE
Confusing Minimum Order Size

### ISSUE THREAD

**Issue by ImGroovin** [Loopring/dexwebapp#136]
The Minimum Order Size isn't clearly stated anywhere to an unregistered user. Further, after registration the Minimum Order Size is not consistent across the various currencies.

100 LRC currently exchanges for 3.333 USDT
0.05 ETH currently exchanges for 10.47 USDT

With the Minimum Order Size not being (relatively) consistent across the various currencies, it's impossible to fulfill some minimum orders. For example, a user cannot submit a LRC-ETH exchange for only 100 LRC unless they also increase the price to meet the 0.05 ETH minimum.

**Comment by xiaowheat** [comment]
After internal discussions, we won't make any changes for this part. Thanks.
