### ISSUE TITLE
Confusing Experience for Unregistered User

### ISSUE THREAD

**Issue by ImGroovin** [Loopring/dexwebapp#137]
If an Unregistered User navigates to the page (https://loopring.io/trade/LRC-USDT), they can opt out of connecting a wallet (simply close the dialogue). However, it's difficult to explore the functionality of the interface because the various input fields and page tabs are disabled. It would be a more user friendly experience if the various tabs could be explored and the Price/Amount input boxes could be directly accessed.

**Comment by xiaowheat** [comment]
After internal discussion, we won't make any change for this part. Thanks
