### ISSUE TITLE
Inconsistent Interaction with Order Book and Recent Trades tables

### ISSUE THREAD

**Issue by ImGroovin** [Loopring/dexwebapp#139]
Clicking any row in the Recent Trades table fills in ONLY the Price.

For a row in the Order Book ABOVE the Spread, clicking the row fills in the Price, and also fills the Amount with the value shown in the "Sum" column (rather than the value shown in the "Amount" column). Further, clicking the row on the Sum column does nothing.

For a row in the Order Book BELOW the Spread, clicking on the Price fills in ONLY the Price. However, clicking the "Amount" fills the Price and also fills the Amount with the value show in the "Sum" column (rather than the value shown in the "Amount" column).

**Comment by xiaowheat** [comment]
After internal discussions, we won't make any changes for this part. Thanks.

**Comment by ebirbe** [comment]
> For a row in the Order Book BELOW the Spread, clicking on the Price fills in ONLY the Price. 

I can confirm this issue @xiaowheat I replicated what @phins1 says and I think this issue should be reopened.

There is an inconsistent behavior when you click on the orderbook columns:

Why if I click on the "Bid Price" column you fill **_only_** the Price field, but if I click on the "Ask Price" column you fill **_both_** the Price and Amount fields? Do you guys say that it should be the correct behavior? I think no.

Could you double check and reopen this issue, please?
