### ISSUE TITLE
Buy/Sell button becomes enabled when switching tabs

### ISSUE THREAD

**Issue by ImGroovin** [Loopring/dexwebapp#140]
The user can fill in the Price and Amount fields and receive an error such as Insufficient Funds, in which case the Buy/Sell button remains disabled. However, clicking on either the Orders or Account navigation tabs, then clicking on the Trade navigation tab enables the Buy/Sell button while retaining the values that were previously entered.

**Comment by xiaowheat** [comment]
Fixed.
