### ISSUE TITLE
No Indication for Scrollable Sections

### ISSUE THREAD

**Issue by ImGroovin** [Loopring/dexwebapp#141]
There is no noticeable indication to the user that certain sections (Order Book, Recent Trades, Options navigation pane) are scrollable. Without a mousewheel, those sections can be scrolled using keyboard arrows, but that requires clicking in that section which may have unexpected results (such as filling in Price and Amount fields).

**Comment by xiaowheat** [comment]
Won't fix. Thank you for reporting.
