### ISSUE TITLE
Bug - When Connecting wallet

### ISSUE THREAD

**Issue by RydalWater** [Loopring/dexwebapp#142]
I used the Brave browser (built in wallet) to connect my wallet. Upon initially navigating to the site you get a pop-up window for connecting the wallet (great, working as intended). If, however, you close this window then it isn't possible to get it back. Indeed, if you click connect wallet and select meta-mask nothing happens. As a result you need to close out of the window or open up a new tab and go to loopring.io again to be able to get the login to the wallet and connect. It isn't immediately clear why this is happening. Hopefully a quick fix.

Cheers

Address in case of bounty: 0x46B756702b865AF30Cc0edba27e6d550e775A904

**Comment by xiaowheat** [comment]
It's fixed.

**Comment by Mynima** [comment]
Great, thanks for fixing. Guessing no bounty for finding/reporting?

**Comment by xiaowheat** [comment]
No. Thanks for reporting the issue.
