### ISSUE TITLE
Pending withdrawal not appearing in the Account

### ISSUE THREAD

**Issue by RydalWater** [Loopring/dexwebapp#144]
I've just requested a withdrawal of some DAI and found that it isn't appearing in the withdrawal section of the account, despite appearing as pending in my own wallet.
 
![image](https://user-images.githubusercontent.com/62206239/80948009-2e2fc380-8de9-11ea-80ee-fc860e10751d.png)

**Comment by xiaowheat** [comment]
If it's pending in your wallet, Loopring.io won't get any data nor show any data. Only the transactions are confirmed on Ethereum will show in Loopring.io

**Comment by Mynima** [comment]
Thanks for the reply.
