### ISSUE TITLE
correct password show's as invalid, does the password expires automatically after a certain amount of time?

### ISSUE THREAD

**Issue by ruhaise** [Loopring/dexwebapp#145]

**Comment by xiaowheat** [comment]
Please reset password. More details on https://medium.com/loopring-protocol/loopring-exchange-frontend-password-bug-postmortem-cf55ce7e0150

**Comment by ruhaise** [comment]
ok, it shows you guys charge no transaction fee for this, but thats not true 
![image](https://user-images.githubusercontent.com/25627383/81386158-d8268d00-9114-11ea-8f2a-9628ec4cba25.png)

**Comment by ruhaise** [comment]
this is the screenshot from the reset screen
![Screenshot 2020-05-08 at 10 17 11](https://user-images.githubusercontent.com/25627383/81386444-4a976d00-9115-11ea-9332-c44f443569ea.png)

**Comment by xiaowheat** [comment]
@ruhaise  We will reimburse all fees in resetting password once we finalize how to reimburse and all effected users.
