### ISSUE TITLE
not possible to login anymore, it says that need to reset account key

### ISSUE THREAD

**Issue by ruhaise** [Loopring/dexwebapp#147]

**Comment by ruhaise** [comment]
![image](https://user-images.githubusercontent.com/25627383/81923797-7ebfd180-95de-11ea-988d-7f0faeb7b1dc.png)

**Comment by enuoCM** [comment]
同样遇到这个问题。之前已经重置过一次密钥。

**Comment by ruhaise** [comment]
@dong77 can you please help here. as this process cost money and i don't have enough in my wallet

**Comment by dong77** [comment]
You do need to reset your account key before you can start trading, but if you don’t do it now, your deposit is still safe. The current gas price is too high, if you don’t want to trade now, you can wait for a couple of days. Resetting account key doesn’t cost anything more than an Ethereum transaction.

**Comment by ruhaise** [comment]
Is it just me who has this problem or everyone? Also the transaction cost
money which i believe is a not communicated cost right?

**Comment by enuoCM** [comment]
@ruhaise @dong77 I have reset my account key by [Tx](https://etherscan.io/tx/0x929d1feea337a0e65558789a226169b725e0385658f15260b7e2006edebc11af) . I still have this problem. What should I do? Reset again??

**Comment by enuoCM** [comment]
I have to reset again. It works!

**Comment by xiaowheat** [comment]
It's resolved.
