### ISSUE TITLE
充值总是不成功问题

### ISSUE THREAD

**Issue by tianheng2017** [Loopring/dexwebapp#15]
充值问题：充值已失败三次，转账hash分别为：https://etherscan.io/tx/0x527a1b55ab286ad544b939d3353dcb2ba4618cba6dc9b5c0d9f85015c48fd201
https://etherscan.io/tx/0xade90a2183a321aa5292ae59c5158bce88a4a9e1243b26dfb838435252e78e1a
https://etherscan.io/tx/0xc8257af6ec894cf981647cb4b8b13d55d47b8a46bb20e9d3b530ef80373e3a3e

**Comment by dong77** [comment]
这个问题之前有人反馈过，现在的版本应该是fix了。

**Comment by dong77** [comment]
给奖励，请给个ETH地址。

**Comment by tianheng2017** [comment]
> 给奖励，请给个ETH地址。

0xC11956A97cf08e1cB48AAB895dB05f7AbD2523aD
