### ISSUE TITLE
建议将“账号”，改为“资产”，账号相关统一放在右侧抽屉即可。

### ISSUE THREAD

**Issue by petergaoxl** [Loopring/dexwebapp#153]
<img width="1288" alt="截屏2020-06-04 上午11 52 59" src="https://user-images.githubusercontent.com/4568033/83713199-0fc41e80-a65a-11ea-96da-d9f0f06a5537.png">

**Comment by xiaowheat** [comment]
经过内部讨论，这个建议没有被采纳。谢谢
