### ISSUE TITLE
有效订单、历史订单、成交记录、充值记录、提现记录细节问题

### ISSUE THREAD

**Issue by tianheng2017** [Loopring/dexwebapp#16]
有效订单、历史订单、成交记录、充值记录、提现记录缺少loading图层，网络不好话打开就是空白的还以为系统有问题呢，实际上过很久条目会出来，建议加上loading层，让用户知道页面正在获取信息

**Comment by xiaowheat** [comment]
建议描述的功能，在现在的loopring.io已实现。谢谢。
