### ISSUE TITLE
Extra ETH dispensing from smart contract after consecutive requests of withdrawal

### ISSUE THREAD

**Issue by prometheusminer** [Loopring/dexwebapp#162]
Thanks for your hard work to realize ZK Rollups but please scrutinize into your smart contract about withdrawal or your webpage. Something wrong there enables releasing extra tokens to users after consecutive requests of withdrawal. I cannot replicate the bug but it did happen.

transaction hashes of two consecutive requests are: 0x44140a2727c4bb61dece7f6fea0be796999cf5a5de1f08098a7f924862bd50b3
0x0283127fbd7eb4cace349360624b2b9fed8a802f3bb180e884749c605e8fc5f3

I only have 0.3 ETH in my Loopring account but the smart contract released 0.6 ETH.

**Comment by xiaowheat** [comment]
Could you provide more details?

**Comment by lyddream** [comment]
We found in the history that you have a transaction income about 0.5 ETH, between two withdrawals.
