### ISSUE TITLE
Missed purchase

### ISSUE THREAD

**Issue by Ololosha100501** [Loopring/dexwebapp#165]
Hi! I've bought DXD token 3 times (1-st screenshot), but only first and third are on my balance now, the second has dissapeared, though ETH has spended. 
![1](https://user-images.githubusercontent.com/36081665/84870307-946e5e00-b098-11ea-98fc-43018ffb7e65.jpg)
![2](https://user-images.githubusercontent.com/36081665/84870313-959f8b00-b098-11ea-9fec-f3f2214eb5be.jpg)

**Comment by lyddream** [comment]
could you please tell us you email, we will contract with you.

**Comment by Ololosha100501** [comment]
gallardok@yandex.com

> could you please tell us you email, we will contract with you.

gallardok@yandex.com

**Comment by xiaowheat** [comment]
The issue has been fixed. Closed
