### ISSUE TITLE
Test API to work on Loopring Pay UI without paying real world ETH

### ISSUE THREAD

**Issue by luzzif** [Loopring/dexwebapp#166]
Hi. I'm working on the Loopring Pay UI bounty, and I thought that it would be nice having a testnet on which to try on-chain operations such as deposit and balance (even more so now that the gas price is literally mooning).

I've been informed by Matt that your SCs are deployed on Goerli, and that's super good, but the Loopring's REST API seems to be referring to the mainnet on-chain activity only. Is there a specific test API (and subsequently relayer network) working in Goerli which we can use to experiment a little bit?

**Comment by xiaowheat** [comment]
You can update https://github.com/Loopring/dexwebapp/blob/master/src/lightcone/config/config.json#L9
Using prod:
```
  "prodServerUrl": "api.loopring.io",
  "prodWsUrl":"ws.loopring.io",
```

Using Testnet:
```
  "prodServerUrl": "uat.loopring.io",
  "prodWsUrl":"ws.uat.loopring.io",
```

**Comment by luzzif** [comment]
Quickly tried with the `/api/v2/exchange/info` API and it worked like a charm. Thank you very much for the fast reply, I appreciate it!
