### ISSUE TITLE
[Bounty-related] Invalid ECSDA signature error when trying to transfer

### ISSUE THREAD

**Issue by luzzif** [Loopring/dexwebapp#167]
I'm developing the Loopring Pay's new UI, and as far as API interaction/message signing goes, I just copied the whole lightcone-related code from this repo.
I have a problem when trying to post a transfer. 
Even though I'm using the `wallet.signTransfer` method, all the data used in the transfer signing seems ok, and I'm signing using a Ledger Nano S, I get an `INVALID ECDSA SIGNATURE` response when executing the order through the REST API.
The code of the  action performing the call can be found [here](https://github.com/luzzif/loopring-pay/blob/master/src/actions/loopring/index.js#L203). 
I honestly don't know what I might be doing wrong. 
I'm available for every possible inquiry.

**Comment by lyddream** [comment]
please refer to our docs:https://docs.loopring.io/en/basics/signing.html

**Comment by luzzif** [comment]
I literally didn't change a thing and it started working. Nice.
