### ISSUE TITLE
[Bounty-related] test the ERC20 token allowance request when trying to deposit

### ISSUE THREAD

**Issue by luzzif** [Loopring/dexwebapp#168]
As the title says, I'd love to test the ERC20 token deposit mechanism (which requires the allowance grant from the user) but in order to do that on Goerli I'd need some ERC20 tokens on Goerli. 
I figured for you it would be easy to just send me some LRCs (I saw the contract is deployed [here](https://goerli.etherscan.io/address/0x6621fc9ca6cb25dd1de695fb1221d12350d7d318)). I case, my address on Goerli is `0xa52D85804Bf9e5ccaE8bF596639B93d0983ff82b`.
Thank you in advance!

**Comment by xiaowheat** [comment]
Please see https://goerli.etherscan.io/tx/0x6d1353504c7fd2c44746d9826c548e916f1853f990e5190c260d49b4fa8aacc8 1000LRC has been sent.

**Comment by luzzif** [comment]
I correctly received the tokens, yet the situation does not seem to be reflected through the balances API in test (uat.loopring.io). I see 0 as my LRC balance, even though the related contract's address seems to be correct.
