### ISSUE TITLE
买卖主题色建议

### ISSUE THREAD

**Issue by tianheng2017** [Loopring/dexwebapp#17]
OKEX和aicoin混惯了，和股市不同，币圈买入不应该是绿色色调，而卖出为红色色调吗？目前反过来还有点不适应

**Comment by dong77** [comment]
我们内部一直这个问题讨论了两个星期了。目前的计划的确是统一买卖的颜色（红卖绿买）但中文涨绿跌红，英文反过来。敬请期待。
