### ISSUE TITLE
Approval issue (using Argent Wallet)

### ISSUE THREAD

**Issue by victoriapcy** [Loopring/dexwebapp#170]
Hi, 
Starting from this morning (11am EST), i've been facing the login issue.
When i used safari to access the website, there is no problem in connecting the argent wallet.  But then when i wanted to login to trade, even i click "Approve" in Argent wallet, it still said "login failed".  Please advise, thank you.
Victoria

**Comment by xiaowheat** [comment]
Does it work before?

**Comment by victoriapcy** [comment]
Yes, it worked well before.  The last time i used was yesterday and everything looks normal.

I already tried to use chrome/ safari/ reboot computer/ upgrade ARGENT wallet, all of these doesn't help.  And my friend also try the same in his computer & argent wallet, and he got the same issue.

**Comment by xiaowheat** [comment]
It may be related to infura APIs or wallet connect. We don't have any new release in the past two days.

**Comment by victoriapcy** [comment]
The wallet is well connected.  The only problem is about login to do trade.  Wondering is there anything that we can try to fix the issue?  Thank you.

**Comment by ebirbe** [comment]
Getting this when signing the login transaction:

![Selección_999(063)](https://user-images.githubusercontent.com/442938/85459425-27633880-b570-11ea-83eb-f6e03d31e2a6.png)

Should this be fixed on loopring or Argent's side?

**Comment by lyddream** [comment]
It seams to like that argent limits the request count. Loopring Dex doesn't set limit like this.

**Comment by xiaowheat** [comment]
Please check the version of Argent app. This is a problem from an old version of theirs.
