### ISSUE TITLE
[Feature] List CHI gastoken and enable CHI burning

### ISSUE THREAD

**Issue by danimesq** [Loopring/dexwebapp#172]
By not only listing CHI, and minting it directly in the UI (exchange ETH > CHI), Loopring's contracts should be upgraded to, by user choice ("enable CHI" button, for when GWEI prices are high), burning ETH storage/CHI tokens when doing any onchain/L1 actions, for cheaper fees!

**Comment by xiaowheat** [comment]
Please use this one for token list. https://loopringexchange.typeform.com/to/nWXj6B

**Comment by DaniellMesquita** [comment]
@xiaowheat

Who said this is a token listing request? It's a whole feature suggestion about gastoken for cheaper transactions on Ethereum.
