### ISSUE TITLE
Negative spread in LRC-ETH and ETH-USDTpairs

### ISSUE THREAD

**Issue by ebirbe** [Loopring/dexwebapp#177]
we have sell orders with lower price than the buy orders, so the spread got negative (see image below).

I refreshed the page and it still there.

![Selección_999(089)](https://user-images.githubusercontent.com/442938/87324832-aa880680-c4fe-11ea-832e-08786ad4b9f0.png)

**Comment by ebirbe** [comment]
ETH-USDT also showed negative spread:

![Selección_999(090)](https://user-images.githubusercontent.com/442938/87326805-3dc23b80-c501-11ea-9b8a-f484689f3ca4.png)

**Comment by xiaowheat** [comment]
Fixed.
