### ISSUE TITLE
订单链上查询问题

### ISSUE THREAD

**Issue by tianheng2017** [Loopring/dexwebapp#18]
硬核建议：右侧我的以太地址->在Etherscan上打开按钮弹出的 etherscan.io 已经被墙了，严重影响体验，包括充值提现记录那部分也是这样，建议像IMtoken一样使用：cn.etherscan.com吧

**Comment by dong77** [comment]
目前如果选择的是中文，etherscan用的链接都是cn.etherscan.com。英文就会用etherscan.io。

**Comment by tianheng2017** [comment]
> 目前如果选择的是中文，etherscan用的链接都是cn.etherscan.com。英文就会用etherscan.io。

BUG！中文下并未采用cn.etherscan.com
![image](https://user-images.githubusercontent.com/29515610/75601322-e644a580-5af4-11ea-83a7-eae629a1fb1d.png)
![image](https://user-images.githubusercontent.com/29515610/75601333-05dbce00-5af5-11ea-8dff-86e6b8092234.png)

**Comment by dong77** [comment]
请提供一个ETH地址。

**Comment by tianheng2017** [comment]
> 请提供一个ETH地址。

0xC11956A97cf08e1cB48AAB895dB05f7AbD2523aD
