### ISSUE TITLE
订单薄订单深度问题

### ISSUE THREAD

**Issue by tianheng2017** [Loopring/dexwebapp#19]
订单薄：显示价格和数量2个字段就行了，如果能开发横向的柱状深度图做背景那就更好了，目前好像有深度图但是紧靠左侧，效果不好，可以参考：https://www.okex.me/dex-test/spot/trade

**Comment by xiaowheat** [comment]
已更新

**Comment by xiaowheat** [comment]
<img width="527" alt="Screen Shot 2020-02-29 at 9 56 30 PM" src="https://user-images.githubusercontent.com/18495858/75620478-59bed500-5b3e-11ea-9703-62afaab369dc.png">
