### ISSUE TITLE
NIOX balance disappeared and is blocked for new trades

### ISSUE THREAD

**Issue by ebirbe** [Loopring/dexwebapp#202]
I'm feasing an issue with my trading balance while running the bot on the liquidity mining campaing. I have a 50/50 distribution on the pair NIOX/ETH running on a bot, but suddenly the bot stopped with a relayer error, and now I can't see my balance to convert back my NIOX balance to ETH.

If I see my balance in the "Trade" tab, it says I have no NIOX to trade, but if I check my balance in the "Account" tab it shows the right value of NIOX I own:

![Selección_999(286)](https://user-images.githubusercontent.com/442938/95633058-e165ae00-0a54-11eb-8c93-7ae1d9baa2a2.png)

![Selección_999(287)](https://user-images.githubusercontent.com/442938/95633075-ea567f80-0a54-11eb-9b87-5b5bd53d5a39.png)

![Selección_999(288)](https://user-images.githubusercontent.com/442938/95633087-f04c6080-0a54-11eb-8de8-99d248cd317c.png)

I thought it was an issue with UI interface only, but I reloaded, signed out/in, and it's the same. And, it also happens with the bot itself:

![Selección_999(289)](https://user-images.githubusercontent.com/442938/95633350-7ec0e200-0a55-11eb-9fab-a51f861a2b75.png)

Could you help me to solve this, please?

**Comment by ebirbe** [comment]
I found this line in the orders history, it says failed:

![Selección_999(292)](https://user-images.githubusercontent.com/442938/95642009-d1a99200-0a73-11eb-8bf7-18023f9d9ab6.png)

Unsure of what that means.

Time on the image is GMT-4, maybe you can check account number 1475 if it helps.

**Comment by mmmmmagina** [comment]
@ebirbe Actually this order is success in our system and matchengine. So you can see the balance is freezed. But there si  something wrong with the view  of order status . We will check and fix that. Thanks for your issue.

**Comment by ebirbe** [comment]
@mmmmmagina Thanks.

Now I am able to trade as usual. I can confirm this issue was fixed.

:+1:
