### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by autumn8** [Loopring/dexwebapp#203]
Hi,

I would like to create a PR for a small enhancement, however there is no contributing.md so could you give me some direction on your PR process. 

(The PR I want to create is simply to add  a link to the market on the order pages so market column entries link directly to the relevant trade page 'trade/${market-pair}' instead of being plain text. 

This allows the user to navigate directly to a specific market instead of having to go via then menu & then selecting market from dropdown. Its a small change but I  find this quite useful & I think other users might too.)

**Comment by xiaowheat** [comment]
Please submit a PR. We will review it.
