### ISSUE TITLE
graph issue

### ISSUE THREAD

**Issue by mfinestone** [Loopring/dexwebapp#207]
When zooming out, the timeline does not become appropriately sized, and it is not movable to see more history. Half the graph space can turn empty.

![image](https://user-images.githubusercontent.com/36642873/98488056-f882f180-21f4-11eb-8f3d-75337627a0a7.png)

**Comment by xiaowheat** [comment]
Works for me.

Click and drag the graph.

**Comment by mfinestone** [comment]
You're right. I guess I expected that if I scrolled sideways it should do the same. Didn't realize must click and drag. Thanks.
