### ISSUE TITLE
Allow switching of pricing terms

### ISSUE THREAD

**Issue by mfinestone** [Loopring/dexwebapp#210]
So you can see a price of LRC in ETH terms, and ETH in LRC terms, etc. 

As users say here:

![image](https://user-images.githubusercontent.com/36642873/103727007-30fe3c00-4fa8-11eb-8625-c6854ad72d98.png)

**Comment by xiaowheat** [comment]
It will be ship in one day.

**Comment by xiaowheat** [comment]
shipped
