### ISSUE TITLE
充值和提现全选问题

### ISSUE THREAD

**Issue by tianheng2017** [Loopring/dexwebapp#22]
充值提现弹窗页面，选择数量部分应该增加一个全部按钮，因为不是每个人都能知道点击余额就能自动填充到数量input框的

**Comment by dong77** [comment]
给奖励，请给个ETH地址。

**Comment by tianheng2017** [comment]
> 给奖励，请给个ETH地址。

0xC11956A97cf08e1cB48AAB895dB05f7AbD2523aD
