### ISSUE TITLE
"Failed to unlock your account on layer-2. Please try again."

### ISSUE THREAD

**Issue by k-falk** [Loopring/dexwebapp#221]
Problem occurs when trying to unlock wallet on Loopring website. 

Steps:
While on exchange.loopring.io click on address at top right with a lock icon next to it. 
Hit "Unlock"
Hit "Unlock" again. (Confirm address is the same one as you have in metamask)
Hit "Sign" on Metamask
Get this error

![loopring problem](https://user-images.githubusercontent.com/4120453/107133829-483b8c80-68ba-11eb-9d53-55874edf7b96.PNG)

Using Metamask on Chrome

Metamask Version: 9.0.4
Browser: Chrome 88.0.4324.146 

Note: Also tried unlocking using MEW for the same address and that did not work either.

**Comment by k-falk** [comment]
This issue was fixed by resetting key pair.

**Comment by pvkpgp** [comment]
> 此问题已通过重置密钥对解决。

我这里“重置密钥”也需首先解锁二层账户！

**Comment by navneetlakra** [comment]
I am getting the same error. In my case I dont get a prompt to sign in metamask. When I try to rest the key I see the following screen.
![image](https://user-images.githubusercontent.com/10936810/107636888-6b52ab80-6cc1-11eb-8580-d7d5e7e2473a.png)

The `you need to pay the following amount` dropdown is blank. When I click on Reset Layer 3 Keypair button I get `Please try to reset your account again!`

**Comment by pvkpgp** [comment]
> > 此问题已通过重置密钥对解决。
> 
> 我这里“重置密钥”也需首先解锁二层账户！

今天晚上突然正常了，我什么也没动！
