### ISSUE TITLE
我的这个账户：0x0Fa74724BD26B8C37424a95dD95F915DDBC9B2AD，二层解锁总是失败！

### ISSUE THREAD

**Issue by pvkpgp** [Loopring/dexwebapp#223]
你好：
我的这个账户：0x0Fa74724BD26B8C37424a95dD95F915DDBC9B2AD，二层解锁总是失败！
进不到二层。提示：“未能解锁二层账户！。。。请再试一次”。重试一直这样提示。不知什么问题！
望解决为盼！   
 
麻烦，谢谢！

**Comment by xiaowheat** [comment]
参照这个 https://github.com/Loopring/dexwebapp/issues/221 解决
