### ISSUE TITLE
Failed to Unlock Account on Layer 2

### ISSUE THREAD

**Issue by navneetlakra** [Loopring/dexwebapp#224]
I am not able to unlock my account. I have around 1 Ether worth of LRC on Layer 2 which I purchased earlier today using Loopring Swap (connected with Metamask). 

However, later in the day when I tried to access my account I get an error saying "Failed to unlock your account on layer-2. Please try again!"

**Comment by cloudrck** [comment]
Same issue here. I've tried to unlock my Layer 2 account for the first time and it's failing.

**Comment by xiaowheat** [comment]
@navneetlakra  Could you retry? The relayer was in maintenance at the time.

**Comment by xiaowheat** [comment]
@cloudrck For your issue, please refer to https://github.com/Loopring/dexwebapp/issues/221

**Comment by navneetlakra** [comment]
thanks for your response. It worked after sometime. I checked #221
<https://github.com/Loopring/dexwebapp/issues/221> for details.

**Comment by cloudrck** [comment]
> @cloudrck For your issue, please refer to #221

Is resetting the layer-2 keypair something I need to do every time I want to access the account?

**Comment by xiaowheat** [comment]
@cloudrck only one time
