### ISSUE TITLE
Your transfer request is failed, please try again

### ISSUE THREAD

**Issue by Amosiam** [Loopring/dexwebapp#225]
Hi,

I've tried multiple times to transfer LP-ADX-ETH and LP-ADX-ETH from my Ledger to Metamask address. Each time I attempt this I'm asked to sign in MM and then asked on the Ledger to sign. This works fine.

However, after signing there is a pop-up with a red ghost stating "Your transfer request is failed, please try again".

Is this a common issue with L2-L2 transfers?

![image](https://user-images.githubusercontent.com/76036936/107873917-d55b9280-6f05-11eb-9594-1023e1e4a8c2.png)

Cheers

Nick.

**Comment by xiaowheat** [comment]
@Amosiam  Looking. It should be fixed in 24 hours.

**Comment by Amosiam** [comment]
Hi, it appears i can transfer tokens/assets but not any LP tokens. Keen to hear if this is going to be fixed?

**Comment by xiaowheat** [comment]
@Amosiam could you try again? LP tokens transfer configurations are just updated.

**Comment by Amosiam** [comment]
Yep - all sorted. Nice work! Thanks.
