### ISSUE TITLE
RGT coins not showing in my wallet

### ISSUE THREAD

**Issue by Shiiike** [Loopring/dexwebapp#232]
I have posted on Discord but no one seems to be able to help me. I moved RGT coins from my metamask wallet into my LRC wallet via the Loopring exchange. Everything worked fine but the coins have never shown up. If I look in Zapper or Zerion the coins are in my lRC wallet but I can't see them in eithe rmy L1 or L2. Is there something I need to do to have them show up? 
Thank you

**Comment by xiaowheat** [comment]
What is your address?

**Comment by Shiiike** [comment]
0xc21b71a52d76541aadb9f80644bdd0918cd69fc7

**Comment by xiaowheat** [comment]
Is it iOS or Android?

**Comment by Shiiike** [comment]
Android but it wont show on the exchange either.

**Comment by xiaowheat** [comment]
Do you have transaction id?

**Comment by Shiiike** [comment]
If its any help, In Zerion the coins show up but in a separate bit that says other assests 'LRC exchange'. 
![RGT](https://user-images.githubusercontent.com/31402686/109917010-57b6c580-7d00-11eb-8063-ffbd226af7e2.png)

**Comment by xiaowheat** [comment]
link?

**Comment by Shiiike** [comment]
https://etherscan.io/tx/0x6403f8f7ee3edba76398a4f2c1023c4cd9ed29f061719442367bd60e1fa23b97

**Comment by Shiiike** [comment]
Okay, not sure if you did anything but the coins ae now showing up in L2 on Metamask.

**Comment by Shiiike** [comment]
Okay. All fixed. Was that you on discord? If so, thank you. Greatly appreciated.

**Comment by Shiiike** [comment]
All fixed with some help.

**Comment by xiaowheat** [comment]
no problem. He is another engineer at Loopring.
