### ISSUE TITLE
Unable to Unlock wallet using MEW mobile wallet dApp

### ISSUE THREAD

**Issue by odesium** [Loopring/dexwebapp#237]
Within the MEW Android mobile wallet Loopring Exchange is displayed as a featured dApp.

![image](https://user-images.githubusercontent.com/56487762/111866344-bae16280-8964-11eb-97ed-6533c8a0aa2b.png)

After clicking the dApp the wallet connects and shows the Unlock button to continue. After signing to unlock, the wallet does not Unlock the L2 account and is stuck on the waiting for the approval screen. No further approvals are received. Same after exiting and rebooting.

![image](https://user-images.githubusercontent.com/56487762/111866382-009e2b00-8965-11eb-8642-02cd464732aa.png)

MEW works fine on the PC web version but not on the Android mobile version.

Using Samsung running Android v8.

**Comment by odesium** [comment]
Issue resolved with MEW app 1.2.9

**Comment by xiaowheat** [comment]
Great!
