### ISSUE TITLE
Exchange orders not being executed in correct order

### ISSUE THREAD

**Issue by odesium** [Loopring/dexwebapp#257]
https://discord.com/channels/488848270525857792/807764093998071878/914084568791924747

![image](https://user-images.githubusercontent.com/56487762/143851190-eb9a7ddd-5f3c-424f-b89a-711d50b3bf9b.png)

**Comment by YoGhurt111** [comment]
### 问题解释
这个人下的订单是orderbook的订单（hash：0x0dbad04b59343fbfa11c8886997e41a4766aa16be741dbadf0a32c37cd516109），而他圈出来的三条成交记录是纯AMM订单（猜测是老页面中下的AMM的订单），对应的订单分别是：0x1c085c4bc469a29489ac780c291f6131415e23d9247d48f10f19de426fe5840b，0x14df564014f89498ab127ce48a61a681c952fa15fcf0f0a4635902d9dabbca6b，0x2b0ab185d766042e3fa8533eb072f07748a55ed38a9906db2a53442f4d483f34。这两者的价格存在差异，如果不是融合订单的话，两者的价格是不能互通的。

### 优化建议
1.  我们也可以更改下不看taker的这个只跟池子成交的参数，按照mix来成交，这样对taker来说也更优
2.  成交记录页面中增加对成交类型的描述

**Comment by PeterHeng666** [comment]
先不去做其他优化，目前先这样
