### ISSUE TITLE
Create NFT method uses different metadata naming than standard

### ISSUE THREAD

**Issue by ablankstory** [Loopring/dexwebapp#278]
Hi -

It looks like when a user Mints an NFT using "Create NFT" (aka the simple method), that the generated metadata is not using standard naming.

Create NFT is using the following:

"properties" instead of "attributes"
"key" instead of "trait_type"

As a result, the Traits are not properly generated in UIs such as lexplorer.io or GME Wallet.

Not working example (used Create NFT): https://loopring.mypinata.cloud/ipfs/QmSAKXNq34XL6GGwh7s2cUBswt9G4vM3ywSExkbKMCZtwU
![m2](https://user-images.githubusercontent.com/104391159/171471878-8ed307cc-b73f-4cc7-ab2d-bf0b42534fe1.jpg)

Working example (used Advance Create): https://loopring.mypinata.cloud/ipfs/Qmcn8yRMXaMfXLvvavFbsntytxC4cu36qq9aKutDxESesc
![m3](https://user-images.githubusercontent.com/104391159/171471963-9223c64a-a4be-4ad5-ac29-2f13556ed9a5.jpg)

Can we please look into this as it will impact any NFTs being minted right now when using Create NFT.

**Comment by ablankstory** [comment]
Additional external link via opensea where it discusses standards: https://docs.opensea.io/docs/metadata-standards

The relevant section on the link is labeled "Attributes" where it discusses labels and naming convention.

**Comment by Jye924** [comment]
> Hi -
> 
> It looks like when a user Mints an NFT using "Create NFT" (aka the simple method), that the generated metadata is not using standard naming.
> 
> Create NFT is using the following:
> 
> "properties" instead of "attributes" "key" instead of "trait_type"
> 
> As a result, the Traits are not properly generated in UIs such as lexplorer.io or GME Wallet.
> 
> Not working example (used Create NFT): https://loopring.mypinata.cloud/ipfs/QmSAKXNq34XL6GGwh7s2cUBswt9G4vM3ywSExkbKMCZtwU ![m2](https://user-images.githubusercontent.com/104391159/171471878-8ed307cc-b73f-4cc7-ab2d-bf0b42534fe1.jpg)
> 
> Working example (used Advance Create): https://loopring.mypinata.cloud/ipfs/Qmcn8yRMXaMfXLvvavFbsntytxC4cu36qq9aKutDxESesc ![m3](https://user-images.githubusercontent.com/104391159/171471963-9223c64a-a4be-4ad5-ac29-2f13556ed9a5.jpg)
> 
> Can we please look into this as it will impact any NFTs being minted right now when using Create NFT.

When did you mint NFT using Create NFT? 
We have fixed this bug in the latest version.

**Comment by ablankstory** [comment]
@Jye924 - I didn't mint it personally, this came from a user in discord. But here is a link to the mint:

https://explorer.loopring.io/tx/22008-300, which should have the date and time it was minted. 

Thanks for looking into this!
