### ISSUE TITLE
移动网络下一些页面请求无法成功问题

### ISSUE THREAD

**Issue by LxzLLL** [Loopring/dexwebapp#29]
在移动网络带宽100M，页面加载一些请求（例如tokenBalances、ethNonce等）时无法成功，导致 

1. 页面充值金额长时间不显示或错乱
2. 在交易完成后（其他网络实际完成，开两台不同网路电脑操作），金额不及时更新，致使错过下单时机
3. 充值页面无法获取地址中eth、lrc等金额
4. 充值页面一部分币种被加载，切换其他币种时显示上一个币种的数据量

建议这样的“数据获取到展示”的一连串功能不要做成异步的，而做成同步加载，未加载完成时给用户提示；而且希望服务器节点放一些在国内，因为有些网络因为运营商的问题，同样的地址同样的带宽会导致访问速度有非常大的差异，也有可能一些网络根本访问不了。

**Comment by dong77** [comment]
这个问题不是那么容易解决。国内网络环境太复杂，太差劲了！
