### ISSUE TITLE
两个账号充值，UI会忽略其后账号的token授权，导致充值失败

### ISSUE THREAD

**Issue by davidqw** [Loopring/dexwebapp#3]
充值时，同一浏览器metamask多个账号切换时。当第一个账号完成授权并充值后，切换到第二个账号进行充值时，会忽略token授权的交易，直接跳入充值流程导致失败

**Comment by davidqw** [comment]
流程是：充值 → 选择资产 → 点击账户余额填充数量。

手动输入数量则正常进入授权流程

**Comment by dong77** [comment]
@lyddream 请确认一下。

**Comment by lyddream** [comment]
确实存在，已经修复。

**Comment by dong77** [comment]
请提供Ethereum地址

**Comment by davidqw** [comment]
> 给奖励。请把你的以太坊地址分享一下给我。
Thanks
0xe4B424E1cCc6f08768C921455F83181bacBfE3F0
