### ISSUE TITLE
充值确认问题

### ISSUE THREAD

**Issue by tianheng2017** [Loopring/dexwebapp#30]
充值成功后，在充值页面状态字段显示“确认中”，建议修改为 0/10  这种，用户可以实时的关心已经确认多少了

**Comment by dong77** [comment]
和中心化交易所不同，我们除了10个确认，还有很多零知识证明相关的中间装填，如果都列出来，一是confuse用户，另外就是界面更复杂。我们目前倾向于细节不那么多，后续我们在看看要不要调整。

目前的判断不显示确认数量。
