### ISSUE TITLE
5个又粗又大的纵向滚动条

### ISSUE THREAD

**Issue by founder-cn** [Loopring/dexwebapp#31]
Chrome浏览器V80.0，深色背景下5个又粗又大的纵向滚动条（详见附件），很影响美观，建议改进
![five-vetical-scrollbar](https://user-images.githubusercontent.com/35712762/75523548-32391100-5a47-11ea-91a9-d7f30b2437ac.jpg)

**Comment by founder-cn** [comment]
![5个纵向滚动条](https://user-images.githubusercontent.com/35712762/75523328-c5257b80-5a46-11ea-955f-4316b70cba78.jpg)

**Comment by dong77** [comment]
这个已经修复了，可能还未来得及发布。

**Comment by dong77** [comment]
这个之前有更早的issue报告： https://github.com/Loopring/dex-ux/issues/31

**Comment by tianheng2017** [comment]
0xC11956A97cf08e1cB48AAB895dB05f7AbD2523aD

**Comment by dong77** [comment]
@founder-cn 请给个地址领取奖励！谢谢。

**Comment by founder-cn** [comment]
0x2915A80711C808723a188C61b3C27F9e0387e9A2, thanks!
