### ISSUE TITLE
下单区域的位置和布局建议

### ISSUE THREAD

**Issue by founder-cn** [Loopring/dexwebapp#32]
目前下单区域在最左边，很不符合操作习惯。建议最左边调整为交易对列表，如LRC-ETH，ETH-DAI等；把下单区域移动到【有效订单】附近，并排放置
![layout](https://user-images.githubusercontent.com/35712762/75524375-bcce4000-5a48-11ea-9c7c-461df725eb14.jpg)

**Comment by dong77** [comment]
每个人的倾向不一样，我喜欢现在的设计。
