### ISSUE TITLE
充值失败

### ISSUE THREAD

**Issue by eddy8** [Loopring/dexwebapp#34]
充值时需要手动填写值，不能点击余额。否则失败，群里也反馈过。

**Comment by dong77** [comment]
这是个好的反馈。目前应该是已经fix了。给奖励。

**Comment by eddy8** [comment]
> 这是个好的反馈。目前应该是已经fix了。给奖励。请把你的以太坊地址分享一下给我。

0x9E4D9A4e14e422E8a8Df8fcA6B6B729F9043a69A

@dong77
