### ISSUE TITLE
Can't deposit ETH and Loopring token

### ISSUE THREAD

**Issue by lamart1** [Loopring/dexwebapp#35]
I see ETH and LRC on Balance on Ethereum, but can't Deposit it. (using Brave beta)
![loop dep](https://user-images.githubusercontent.com/10207118/75541096-95ae4900-5a1d-11ea-857f-f9dba0b32263.png)

**Comment by dong77** [comment]
Can you describe your operations?

**Comment by lamart1** [comment]
I think it is due to some Ledger Linux bug. On my PC it is working now properly.
