### ISSUE TITLE
谷歌浏览器自动翻译造成白屏

### ISSUE THREAD

**Issue by Samjii** [Loopring/dexwebapp#36]
我WIN10系统的谷歌浏览器浏览多数的中文网站都不会出现自动翻译网站，路印去中心化网站则出现了谷歌翻译，翻译后或者“显示原始网页”刷新，经常出现屏幕空白没东西，后来我设置谷歌“一律不翻译此网站”后一切正常，不管是初次打开还是重复刷新，再没出现白屏情况。但普通用户并不一定会这样设置，因此中文的化应该改一下编码格式，别让谷歌做自动翻译。

**Comment by dong77** [comment]
这个问题我们注意下，不过很多网站如果用Google翻译都会有问题。下个版本会禁止自动化的谷歌翻译，因为已经做了中英文双语版本。
