### ISSUE TITLE
版本升级重新注册问题

### ISSUE THREAD

**Issue by Samjii** [Loopring/dexwebapp#38]
这个问题是提前说的。“路印交易所升级使用不同的智能合约”如果账户已经在旧合约注册了，升级后新的合约要重新注册的话，不应该再收取0.0036ETH的注册费，否则就有涉嫌骗取注册费之嫌，给路印造成的影响极坏。最好是能将注册账号无缝过渡到新合约里面，避免用户流失

**Comment by dong77** [comment]
这个是协议的技术限制。是否去注册用户有选择权，因此没有什么涉嫌骗取注册费之嫌。

**Comment by Samjii** [comment]
1、我理解协议的技术限制，但是否可以由手工操作方式将旧协议的注册账号一次性批量在新协议里注册，不需要用户再进行注册操作？

2、是否去注册选择权是在用户手上，但问题是旧用户已经给过一次注册费了，然后每做一次升级还得再给一次注册费，用户会怎么想？

3、再从路印角度上说，如果每升级一次就重新注册，用户流失率有评估过吗？

这个升级后需要用户付费重新注册这件事务必重视！如果当前技术限制无法解决，那就换个思路去解决，总之办法是人想出来的。

**Comment by Samjii** [comment]
> 这个是协议的技术限制。是否去注册用户有选择权，因此没有什么涉嫌骗骗取注册费之嫌。

1，我理解协议的技术限制，但是否可以由手工操作方式将旧协议的注册账号一次性批量在新协议里注册，不需要用户再进行注册操作？

2，是否去注册选择权是在用户手上，但问题是旧用户已经给过一次注册费了，然后每做一次升级还得再给一次注册费，用户会怎么想？

3，再从路印角度上说，如果每升级一次就重新注册，用户流失率有评估过吗？

这个升级后需要用户评估重新注册这件事有望解决！如果当前技术限制无法解决，那就换个思路去解决，总之办法是人想出来的。

**Comment by dong77** [comment]
> On Feb 28, 2020, at 21:00, ICOACE <notifications@github.com> wrote:
> 
> 这个是协议的技术限制。是否去注册用户有选择权，因此没有什么涉嫌骗骗取注册费之嫌。
> 
> 1，我理解协议的技术限制，但是否可以由手工操作方式将旧协议的注册账号一次性批量在新协议里注册，不需要用户再进行注册操作？
> 
> 

简单的方案是注册需要费用，但老用户我们手工返回费用即可。无需产品上太大改动。
