### ISSUE TITLE
Metamask not binding to loopring.io

### ISSUE THREAD

**Issue by RensR** [Loopring/dexwebapp#42]
Expected behaviour: 

1. Visit loopring.io with an open metamask client
2. Loopring sees metamask and opens communications

Found behaviour:

1. Visit loopring.io with an open metamask client
2. Error message with "You need MetaMask installed before using Loopring Exchange!"

Reproduce by going to loopring while having metamask installed. It does work sometimes as I was able to create an account and deposit funds but now it won't let me trade because it claims there is no metamask installed.

It does show my deposited funds so I'm still "logged in" it's just the metamask connection that isn't workng.

Browser: Chome (latest)

**Comment by RensR** [comment]
Workaround found: swapping accounts in metamask will trigger a reload that refreshing the page does not do.  If you are stuck with a message that metamask is not found please change your account to another address and back to get a login prompt from loopring.io

**Comment by dong77** [comment]
Thank you for the feedback. We are integration with onboard.js, all the current MetaMask specific logic are likely to be removed.
