### ISSUE TITLE
充值和提现希望有更加详尽的状态，文字解释，并且不可反复点击。

### ISSUE THREAD

**Issue by PocketPQ** [Loopring/dexwebapp#43]
比如点击充值后，到重置成功之间，以太坊账户和交易账户都没有这笔钱，也没有提示，就会有人心里发毛。
再比如体现发起后，发起提现按键还可以反复点击生成发起，并且都会提示正常完成。严谨的讲，存在错误的历史记录。比如我只有一笔钱提现成功，另一笔是反复点击，但是我以后再看这个历史记录就会误解为提现两笔都成功了。
![image](https://user-images.githubusercontent.com/61608713/75599453-ef774780-5adf-11ea-8f10-160fe8bda25e.png)

另外，可以在充值记录，提现记录，账户余额三个页面下方空间增加解释文字，比如“根据反馈，提现到账大约1.5小时成功一批之类的。”

产品PQ

**Comment by dong77** [comment]
充值提现的请求目前是通过以太坊tx发起的，因此交易所只有在以太坊确认了用户转账后才知道真的有这样一个请求。后续支持offchain请求这个状态就是瞬间的了。别着急，快上线了。

另外即使你有10个eth在交易所，你也可以发起多次提现1000个eth的请求，因为以太坊在你提现的那个时刻也不知道你在交易所那个瞬间的余额。这是”拉婴儿2”的特点。绕不过去。

**Comment by dong77** [comment]
最后一个建议是我们已有的计划，后台正在实现。但优先级不高。

**Comment by PocketPQ** [comment]
程序我不大懂啊。我想web端既然有点击，二次点击就可以toast之类的让用户知道。并且两次提现都提示完成应该可以避免吧。这不是正不正确的问题，而是用户体验问题。可以想办法让用户不迷茫的。

**Comment by dong77** [comment]
我想弄明白你说的二次点击在UI的哪个地方？

**Comment by PocketPQ** [comment]
dex-账号-账号余额-提现

**Comment by dong77** [comment]
我没有办法二次点击呀...
