### ISSUE TITLE
产品优化建议：增加价格加减按键，和一个创意的取整按键。(有效果图)

### ISSUE THREAD

**Issue by PocketPQ** [Loopring/dexwebapp#44]
![image](https://user-images.githubusercontent.com/61608713/75600115-8ba44d00-5ae6-11ea-9009-3e2aca72c9e0.png)
如图，参考币安增加价格末位数加减按键，我认为很常用。另外在100%右侧加上一个创意的“取整”按键。可以根据开发人员兴趣加一点逻辑，多次点击有不同的效果。比如666.66，第一次点击变成700.00，第二次点击变成600.00,第三次点击变成666，第四次点击变成660。哈哈

**Comment by xiaowheat** [comment]
经过内部讨论，这个建议没有被采纳。谢谢
