### ISSUE TITLE
目前web宽度1000以下页面dex不可用，不太复杂的解决建议

### ISSUE THREAD

**Issue by PocketPQ** [Loopring/dexwebapp#45]
目前宽度1000以下会选择隐藏订单池，
1、1080p显示屏，windows半屏显示功能960像素，正好不可用，还需要手动拖动，以至于另外半屏也要拖动。
![image](https://user-images.githubusercontent.com/61608713/75600971-49343d80-5af1-11ea-9a06-24d39879ce37.png)

如果我的订单放在下面，或者在一定屏幕宽度之内放在下面，这个问题就解决了。

2、并且也方便了手机屏幕浏览，轻松做到16：9，在全面屏手机上钱包浏览器里，体验基本不打折扣。即便路印出了钱包，还是有人更喜欢用其他钱包，也是互相渗透互相了解的宣传过程。更多的合作而不是自己干，才会让别的社区看到并深入了解。

3、另外这个图片我还做精简了我的持仓，只是把订单大小处做了颜色提醒。也可以鼠标悬停显示或交替显示等方案。哪一行太占空间且用处较小。

**Comment by dong77** [comment]
响应式的布局下一步会统一做调整。感谢您的反馈。
