### ISSUE TITLE
关于“登出”按钮建议

### ISSUE THREAD

**Issue by tianheng2017** [Loopring/dexwebapp#46]
**登出，有点别扭， 改成 “退出登录”或“退出”如何**  
![image](https://user-images.githubusercontent.com/29515610/75601471-7505f200-5af6-11ea-8fc3-cd0dd89cf11d.png)  
![image](https://user-images.githubusercontent.com/29515610/75601502-bc8c7e00-5af6-11ea-93c7-7bdb05023335.png)

**Comment by PocketPQ** [comment]
这个细节不错，非计算机专业人士看到会更好理解一些。虽然这种小问题~~

**Comment by dong77** [comment]
采纳了，不过太小的细节了，我就不给你奖励了。很感激！
