### ISSUE TITLE
时间格式不对应问题及建议根据用户的区域特性设置相关界面显示

### ISSUE THREAD

**Issue by LxzLLL** [Loopring/dexwebapp#47]
1、主页面“有效订单”，“历史订单” 和 ”订单”中的“有效订单”，“历史订单”，“成交记录”的时间格式不同，建议修复为相同格式的日期。
2、另建议中英文切换的时候，根据浏览者的语言和区域特性不同，将日期等格式设置为对应区域特性的，增加良好的用户体验

**Comment by LxzLLL** [comment]
eth address：0xf39641be7e317b7de4e5827f724a1f28f6d5eea0

**Comment by dong77** [comment]
给个地址领取奖励吧。

**Comment by dong77** [comment]
已经修复。

**Comment by LxzLLL** [comment]
Eth address: 0xf39641be7e317B7DE4e5827f724a1f28f6d5eea0 
谢东哥~~
