### ISSUE TITLE
创意：增加“/CNY*”交易对。

### ISSUE THREAD

**Issue by PocketPQ** [Loopring/dexwebapp#49]
/ETH交易对，/USDT交易对当然是必须有的。可以增加一个虚拟的“/CNY*交易对，实际上交易的还是USDT只不过所有价格都换算了CNY，可以每天或如何同步一下汇率，其实就是所有/USDT交易对的映像。

比如现在是正好1：7汇率。我挂单7“CNY*，就是挂单了1个USDT，两边都显示。
中文版页面提供“/CNY*交易对，英文版提供“/EUR*交易对。哈哈

**Comment by tianheng2017** [comment]
嘿嘿  "增加一个虚拟的/CNY*交易对，实际上交易的还是USDT只不过所有价格都换算了CNY" ，感觉行不通，也没必要，只能说通过个人设置改变下最新成交价的换算，像这样
![image](https://user-images.githubusercontent.com/29515610/75601651-2fe2bf80-5af8-11ea-9ed3-ca12a3c3f83c.png)

**Comment by PocketPQ** [comment]
不同观点，比如bitCNY有市场,你以为真的有人想持有bitCNY？他只是希望看到的，下单输入的，都是以rmb为单位。比起加个括号换算让你知道，我的方案更加彻底。

**Comment by dong77** [comment]
有靠谱的人民币稳定币我们就上。
