### ISSUE TITLE
Clicking on the Recent Trades tab and then clicking on Order Book tab will show the user a blank order book.

### ISSUE THREAD

**Issue by timet7** [Loopring/dexwebapp#5]
Clicking on the Recent Trades tab and then clicking on Order Book tab will show the user a blank order book.

If you click twice on the Order Book everything will show up again.

Here's my address if this is accepted: 0x38aC7EA6d2EDFf2d78E5af31B4caF27592b4e094

**Comment by dong77** [comment]
Confirmed, thank you. Please provide an ETH address.

**Comment by timet7** [comment]
> Confirmed, thank you. Please provide an ETH address.

0x38aC7EA6d2EDFf2d78E5af31B4caF27592b4e094

Thanks!

**Comment by xiaowheat** [comment]
Fixed
