### ISSUE TITLE
K线图表功能问题及建议

### ISSUE THREAD

**Issue by LxzLLL** [Loopring/dexwebapp#50]
K线图表功能太简单，
1、k线颜色与量能颜色反了
2、没有分钟、小时、天、周、月级别的K线
3、没有一些可用于分析的简单画图工具

建议整个稍微专业一点的，例如 
![3](https://user-images.githubusercontent.com/9365687/75601748-345ba800-5af9-11ea-9d75-a5caeeeb66cb.png)

**Comment by dong77** [comment]
K先会改进。但不会那么”专业“，其实那些划线的都是扯淡。

**Comment by dong77** [comment]
K先是我们内部计划整体重新做的一个事情。谢谢您的反馈。
