### ISSUE TITLE
订单提交失败问题

### ISSUE THREAD

**Issue by LxzLLL** [Loopring/dexwebapp#52]
订单提交成功有，已经存在有效订单列表中，但还会提示出来“订单提交失败”。
而且还有一些几率实际已经提交成功，但未在有效订单列表且也提示“订单提交失败”，但刷新后提交的订单出现在有效订单列表中。
以上问题，怀疑与网络延迟有关，请确认下，因为现在我每次提交订单很大几率会出现上述问题。

**Comment by dong77** [comment]
这个是已经知道的问题。应该是已经被fix了。

**Comment by dong77** [comment]
@lyddream 请确认下。

**Comment by lyddream** [comment]
这个是网络超时，实际已经成功了。我们改变一下提示就好

**Comment by dong77** [comment]
网络超时应该是不知道是否成功把？
