### ISSUE TITLE
Minor User Exp

### ISSUE THREAD

**Issue by Pnin1204** [Loopring/dexwebapp#55]
I was creating an account on loopring, to register an account, and I used my default brave browser wallet.  In order to create an account, a fee is charged to register, so I needed to deposit the funds before registering.  Thus, I had to cancel or reject the transaction.

After doing so, trying to navigate was a bit awkward as the popup didn't let me browse the sidebar.  It's not a real bug, as simply closing the popup fixed the issue, but for me, as a user, I wanted to click on the sidebar in order to exit the page naturally.  I've a recorded video of it if you'd like.

**Comment by dong77** [comment]
@kenpole , if you reject the registration tx, the popup should automatically disappear and you should be able to move your cursor to the top-right corner of the app to see the sidebar. Let me know if I missed something...

**Comment by kenpole** [comment]
The popup did not disappear for me.  I'll show you a gif of what I mean here.  Also, I was generation 1st red packet group a couple years ago and have tested all loopring.io experiences.  Glad to see it consistently improving!

Hope you can see this gif and understand what I mean.  It's a very minor "issue", but I hope it helps.


![Loopringminoruserexpsuggestion](https://user-images.githubusercontent.com/35647557/75617961-39dedf80-5b45-11ea-8ff4-30fff4118447.gif)

**Comment by dong77** [comment]
Thank you. I got it fixed. Please share an ETH address for reward.

**Comment by kenpole** [comment]
Thanks so much!  I wasn't expecting one for this one.  Just wanted to let you know.  My ETH address here works: 0x47bFF18E462912Ab61a465b2bc229e3857491AA6
