### ISSUE TITLE
账户余额问题

### ISSUE THREAD

**Issue by eddy8** [Loopring/dexwebapp#56]
取消未成交的订单后，下单页面的资金余额很久不能同步，造成无法下单。但是账号余额页面显示正常余额。重新登录了下，才正常。

**Comment by dong77** [comment]
这个问题是内部已知问题，应该是已经解决了。

请 @lyddream 确认。

**Comment by eddy8** [comment]
> 
> 
> 这个问题是内部已知问题，应该是已经解决了。
> 
> 请 @lyddream 确认。

依然存在这个问题

**Comment by xiaowheat** [comment]
在最新的loopring.io中，未能复现
