### ISSUE TITLE
增加质押和赎回功能建议

### ISSUE THREAD

**Issue by Samjii** [Loopring/dexwebapp#59]
通过操作智能合约方式质押和赎回LRC，需要有一定的智能合约技术，一般用户无法也不敢操作，担心操作不当丢币，这必然对此产品的效果大打折扣。建议交易所上增加简易的质押和赎回功能，这样可以让用户在交易所里购买LRC直接质押，赎回后又可以在交易所里卖出。而且此功能本来就是交易所应具有的

**Comment by dong77** [comment]
这个是已经规划的功能，但是排在比较后面。
