### ISSUE TITLE
The Order Book should realign itself in the center when switching between different trading pairs

### ISSUE THREAD

**Issue by timet7** [Loopring/dexwebapp#60]
The Order Book should realign itself in the center (Last Price should be centered) when switching between different trading pairs. 

Currently it stays in whatever position you had it in before when jumping to different trading pairs. 

More of a quality of life change than a bug but that is how it works on Coinbase Pro for example. 

0x38aC7EA6d2EDFf2d78E5af31B4caF27592b4e094

**Comment by dong77** [comment]
Good suggestion. Will implement.

**Comment by timet7** [comment]
> Good suggestion (The current implementation is very similar to pro.coinbase.com.
> ). Will implement. But this is not a bug as you would agree, so we'll not reward you. But we appreciate this one.

I just noticed this was updated on the exchange. IMO it's way too aggressive now. The order book should only be centered again when you do something like switch to another trading pair. Currently it will force itself to align in the center whenever you scroll up or down the order book.
