### ISSUE TITLE
会员名称显示BUG

### ISSUE THREAD

**Issue by JBC998** [Loopring/dexwebapp#61]
![微信截图_20200301164419](https://user-images.githubusercontent.com/61648020/75622503-f71c1680-5bdb-11ea-8157-2c8822e5ddea.png)
听说别人的名称是“终生荣誉会员”，没有那个问号，但是我的名称是“终生荣誉VIP”，有个问号。 是不是每个人的显示都不一样的？

**Comment by dong77** [comment]
版本升级过程中的缓存问题。不用担心。
