### ISSUE TITLE
记录查询页面的方便性

### ISSUE THREAD

**Issue by loopring1992** [Loopring/dexwebapp#62]
去中心化无国界，后续流量陆续上来，建议可以加日韩等翻译页面，另外在交易记录，历史订单栏里位置建议可以选择页目日期选项的查询方式，方便查询，滑道查询这种方式来查询以往记录一直往下拉个人认为不是很方便望采纳，好事多磨。

**Comment by dong77** [comment]
目前还是产品的早起阶段，目前没有稳定到应该翻译成多过语言的程度。这个后续会做的。感谢您的反馈。

**Comment by dong77** [comment]
订单查询也是后需要做的。
