### ISSUE TITLE
点击账号区域 自动复制账号到剪切板的建议

### ISSUE THREAD

**Issue by tianheng2017** [Loopring/dexwebapp#63]
**希望增加一个功能：点击账号区域可以复制完整的账号到剪切板**，如图  
![image](https://user-images.githubusercontent.com/29515610/75625988-5ab73b80-5bfe-11ea-8058-eee126affaf0.png)

**Comment by dong77** [comment]
谢谢反馈，内部已经有计划，不过优先级较低。
