### ISSUE TITLE
订单薄深度优化建议

### ISSUE THREAD

**Issue by tianheng2017** [Loopring/dexwebapp#64]
优化建议：当前深度是从左向右辐射，因左侧价格内容较多，且价格颜色与深度颜色太相近，非常不够显眼，反而右侧持仓区域却比较空闲，如果能放到右侧视觉冲击必定更好，，，，所以建议将深度从右向左辐射，用户体验更佳，另外深度背景色可以再适当调深一丁点
![image](https://user-images.githubusercontent.com/29515610/75626134-bdf59d80-5bff-11ea-954b-d6b852c04120.png)

**Comment by xiaowheat** [comment]
深度从右向左辐射的设计，不常见。

**Comment by xiaowheat** [comment]
经过内部讨论，这个建议没有被采纳。谢谢
