### ISSUE TITLE
table表格标题和内容居中建议

### ISSUE THREAD

**Issue by tianheng2017** [Loopring/dexwebapp#66]
当前是居左，改为居中是不是更美观点呢？  

当前图：  
![image](https://user-images.githubusercontent.com/29515610/75626676-673e9280-5c04-11ea-91d2-ef719784c216.png)

建议修改：
![image](https://user-images.githubusercontent.com/29515610/75626654-424a1f80-5c04-11ea-9884-39d7765b5e0c.png)
![image](https://user-images.githubusercontent.com/29515610/75626658-4bd38780-5c04-11ea-984e-09ab3cb73ab6.png)

**Comment by dong77** [comment]
谢谢建议。后续会有大的改版。目前还是个beta版。
