### ISSUE TITLE
关于单击订单薄条目自动填充价格的优化

### ISSUE THREAD

**Issue by tianheng2017** [Loopring/dexwebapp#70]
单击订单薄条目的优化建议：  
方案一：点击任何条目，只填充价格，不填充数量
方案二：点击价格只填充价格，点击数量才填充数量  
  
当前OKEX是点击订单薄条目只填充价格  
![image](https://user-images.githubusercontent.com/29515610/75627332-1df14180-5c0a-11ea-9277-38c8ad6e79da.png)

**Comment by dong77** [comment]
这个目前已经有计划（和你第二个方案一样）。感谢反馈。
