### ISSUE TITLE
界面数据未实时更新问题

### ISSUE THREAD

**Issue by LxzLLL** [Loopring/dexwebapp#71]
界面的数据在不操作几分钟或十几分钟后，数据不会再实时更新，必须手工刷新界面

**Comment by dong77** [comment]
@lyddream 我怎么感觉这个bug之前有人汇报过。目前还存在这个问题吗？

**Comment by lyddream** [comment]
可能还是网络问题，导致socket 的建立失败。我尝试复现并Fix优化一下

**Comment by xiaowheat** [comment]
在最新的loopring.io中，未能复现
