### ISSUE TITLE
交易订单价格列表滚动问题

### ISSUE THREAD

**Issue by sl-gong** [Loopring/dexwebapp#72]
交易订单价格列表，鼠标中键滚动时，买单和卖单都同时滚动了，滚跑后，在滚回找买一和卖一，不太好辨认。建议滚动卖单列表和买单列表，中间买一卖一不动。
![image](https://user-images.githubusercontent.com/29905190/75628826-87c41800-5c17-11ea-8180-6c0365cab2dd.png)

**Comment by dong77** [comment]
哪个交易所做的和你建议的一样吗？

**Comment by dong77** [comment]
<img width="268" alt="Screen Shot 2020-03-01 at 17 36 45" src="https://user-images.githubusercontent.com/1710087/75635338-3a2db800-5be3-11ea-8591-da4014a6010e.png">
也许一个更好的方案是这样，就是上面图中的买一卖一以及中间的当前价格也一样滚动，但是滚到屏幕顶端就变得sticky，滚到底部也是sticky。

**Comment by sl-gong** [comment]
就是分两个列表滚动，卖单列表和买单列表，中间不动，中间显示实时交易价

**Comment by xiaowheat** [comment]
综合多方意见，这部分的UI不会改动。
