### ISSUE TITLE
界面语言切换问题

### ISSUE THREAD

**Issue by sl-gong** [Loopring/dexwebapp#73]
语言切换弹出的对话框离当前鼠标太远，选择不方便，而且不显眼。建议改成“简体中文”和“English”，并且贴近当前鼠标。
![image](https://user-images.githubusercontent.com/29905190/75628846-bf32c480-5c17-11ea-8a78-7187d7d71fb2.png)

**Comment by dong77** [comment]
已经有过这个建议。目前优先级很低。
