### ISSUE TITLE
合约账号安全性说明

### ISSUE THREAD

**Issue by sl-gong** [Loopring/dexwebapp#76]
建议提供相关资料说明链接，如果有充分逻辑证明，并公开相关信息更好。解释为什么充值合约账户“0x944644ea989ec64c2ab9ef341d383cef586a5777”，是安全可靠的账户。

**Comment by dong77** [comment]
网站上有链接到“路印协议”。etherscan上面也标记了改地址是路印交易所的beta1地址。
