### ISSUE TITLE
主页面右上角账户系统信息显示问题

### ISSUE THREAD

**Issue by sl-gong** [Loopring/dexwebapp#77]
主页面右上角点开账户相关信息显示问题：没有明显的滚动条，用户需要滚动鼠标中键才能看到下方相关信息及反馈，提示体验不好，看不到滚动条，用户以为就屏幕上这些信息了。

<img width="190" alt="系统信息" src="https://user-images.githubusercontent.com/29905190/75629009-606e4a80-5c19-11ea-82a6-bbe68401eb38.png">

**Comment by dong77** [comment]
该问题已经有人反馈，而且我们内部早就知道这个问题。目前这一块要大改动，所以您的这个建议我就不给奖励了。但还是非常感谢您试用我们的产品。我们会持续优化产品，让大家越用越舒服。
