### ISSUE TITLE
有效订单列表显示问题

### ISSUE THREAD

**Issue by sl-gong** [Loopring/dexwebapp#78]
有效订单列表有多个情况下，不方便浏览全部有效订单，需要鼠标移动进入到订单列表第一个很小的高度范围通过鼠标滚动才能看到其他订单，而且这个高度只能显示一个记录。我显示器分辨率是1080高度。

**Comment by dong77** [comment]
我不是很明白，能截个图 给我说明下吗？

**Comment by sl-gong** [comment]
> 我不是很明白，能截个图 给我说明下吗？

![image](https://user-images.githubusercontent.com/29905190/75748656-f8278200-5d5a-11ea-8d42-8c042c0174da.png)

**Comment by xiaowheat** [comment]
@sl-gong 能不能加一个全屏或者大一点的屏，这个截图太小，我们很难确认屏幕大小
