### ISSUE TITLE
Limit order doesn't fill to best available price

### ISSUE THREAD

**Issue by saurabh** [Loopring/dexwebapp#79]
Lets say the best bid on the order book for LRC-ETH is 0.00017800 ETH/LRC and the next best bid is at 0.00017795. I put a sell order at 0.00017795. Instead of selling to the 0.00017800 first, my order is executed at the second best bid instead. 

I came across this bug because after a few hours, I switched to the loopring tab and sold to the best bid that I saw on the order book. After selling and seeing the 'order placed' notification, I noticed that my eth balance had not updated. I refreshed the page and realized that my order book had not updated and I had sold at a much lower price than the current highest bid.

To recreate: 
Place an order at a lower price than the current best bid/ask.

Here is a screenshot for reference: https://i.imgur.com/NtaHqXL.png

Thanks.

**Comment by dong77** [comment]
I'll need to confirm with the backend team. See this is a valid report to me.

The second one was reported and I think it's already fixed (maybe not deployed)

**Comment by dong77** [comment]
@saurabh can you share your ETH address for the reward?

**Comment by saurabh** [comment]
Hi, my ETH address is ledger47.eth thanks.
