### ISSUE TITLE
Total value in ETH and $

### ISSUE THREAD

**Issue by lamart1** [Loopring/dexwebapp#8]
Can you add sum all in Balance on exchange in ETH and $ ?
Something like on Binance
![Screenshot from 2020-02-27 23-17-22](https://user-images.githubusercontent.com/10207118/75492145-741a7680-59b7-11ea-81a6-01cf6716c7c6.png)

**Comment by dong77** [comment]
It is in our design to display this on the top of the balance table. But it's not a priority for us right now.
