### ISSUE TITLE
挂错单检测和提醒

### ISSUE THREAD

**Issue by Leilalin** [Loopring/dexwebapp#80]
卖单可以增加再次确认吗，以防止挂错单？有挂错单检测吗？比如挂买单超过市价20%

**Comment by dong77** [comment]
我们有计划增加价格提醒，不过再次确认的确没有想过。我们内部要讨论下哈。

**Comment by dong77** [comment]
目前决定需要和用户确认的情况：

- 价格离上一次成交价差距超过20%
- 订单和上一个订单一模一样。

https://github.com/Loopring/dexwebapp/issues/506

**Comment by xiaowheat** [comment]
增加了提醒：价格离上一次成交价差距超过20%

**Comment by dong77** [comment]
给个地址领取奖励吧。
