### ISSUE TITLE
Bar color inconsistent between candles and indicators

### ISSUE THREAD

**Issue by patc20** [Loopring/dexwebapp#83]
Better to make alignment so user don't get lost.

![image](https://user-images.githubusercontent.com/59556853/75648444-0dcd7680-5c8b-11ea-8ec0-e81f26c395b8.png)

**Comment by dong77** [comment]
This has been fixed. Thank you for the feedback. Please provide an ETH address to receive our appreciation.

**Comment by 13767849** [comment]
thank you, my eth wallet address:
0xcCb1443A65911A08B0E0e9B203e0931E8ED853c3
