### ISSUE TITLE
i would like to have Position module besides Orders

### ISSUE THREAD

**Issue by patc20** [Loopring/dexwebapp#89]
for now user have to go to Account page to view his Position, it's wallet style, but as a trading platform, the Position is always besides Orders so that trader can have a better and efficient control over trading management

**Comment by xiaowheat** [comment]
Could you provide a screenshot for what you describe?

**Comment by 13767849** [comment]
example from tradingview also, aka the grid in your Account page

![image](https://user-images.githubusercontent.com/59556853/75660970-6e6aac80-5ca7-11ea-9a29-9909b3521349.png)

**Comment by xiaowheat** [comment]
What is this different from open order on https://loopring.io/orders/open-orders

<img width="1261" alt="Screen Shot 2020-03-02 at 1 49 24 AM" src="https://user-images.githubusercontent.com/18495858/75664874-0e80f100-5c28-11ea-8e8c-2a97761d7af7.png">

**Comment by 13767849** [comment]
Sorry if it was not stated clearly, to clarify, what i mean is to add a new tab here, make orders and position a consolidated view, together with trade board, they are the most frequent accessed modules for a trader.

![image](https://user-images.githubusercontent.com/59556853/75665272-e2f51980-5cae-11ea-86f6-338512ff52e3.png)

**Comment by dong77** [comment]
Seems this is a design decision. We discussed internally and decided not to merge those sub-tabs under one tab. Thank you. @13767849
