### ISSUE TITLE
The order book is too static

### ISSUE THREAD

**Issue by patc20** [Loopring/dexwebapp#90]
i am not reflecting the volatility, but i need something tell me what's going on on buy side and sell side, if there is dynamic indicator like +100 or -200, next to order book Size column, that would be super helpful.

or a secondary solution is to put the arrow icon, up for increment, and down for deduction.

**Comment by dong77** [comment]
I don't think I get it, do you have an example that we can learn from, a picture is worth a thought words :)

**Comment by 13767849** [comment]
With some dynamic effects, trader can better sense the buy/sell pulse.
it's not necessary to duplicate below examples, but it's a nice UX uplift

![image](https://user-images.githubusercontent.com/59556853/75750322-ea73fb80-5d5e-11ea-8484-c0736169a284.png)
![Uploading image.png…]()

**Comment by xiaowheat** [comment]
Using orderbook should work.
