### ISSUE TITLE
建议订单簿从一个列表改成买单和卖单两个列表

### ISSUE THREAD

**Issue by dos2004** [Loopring/dexwebapp#93]
目前订单簿是一个长列表，上下滚动时买单和卖单一起滚动，看起来很不习惯，跟中心化交易化不一样。
希望买单和卖单各一个列表，最新成交价text固定位置不变，买单和卖单列表都可以上下滚动，跟中心化交易所一样。

**Comment by dong77** [comment]
不同的设计，不同的选择。
