### ISSUE TITLE
关于有效订单，历史订单

### ISSUE THREAD

**Issue by aBovine** [Loopring/dexwebapp#95]
1.增加成交数量：有效订单，历史订单都只有成交比例，用户的订单部分成交的情况下要通过比例计算才知道具体成交了多少个代币，不够直观，应增加成交数量的展示。
2.当前委托：有效订单改成当前委托，比较适合中国人的直观思维。

**Comment by dong77** [comment]
两条建议均以采纳。不过都比较小，而且第一点内部已经在做了。第二点我们没注意到。感谢。

**Comment by aBovine** [comment]
接收奖励地址：0x55db43ae45f7a73c6d2842712d7856a356b7e242
