### ISSUE TITLE
有效订单列表优化建议

### ISSUE THREAD

**Issue by LxzLLL** [Loopring/dexwebapp#96]
有效订单列表中只显示交易对的一个币种总额，建议加上另一个币种的总额，因为在使用时，很多情况下需要做个参照，买这个币种花了多少个交易对中的另一个币种，例如如下：
LRC/ETH交易对：界面中只显示了LRC的总额与成交百分比，但不能直接得出买/卖这些LRC  花费/获得多少的ETH，需要自己通过计算得出。
针对上述例子 建议加上一个“总额/已完成（ETH）”的列

**Comment by xiaowheat** [comment]
经过内部讨论，这个建议没有被采纳。谢谢
