### ISSUE TITLE
Fees are incorrectly displayed in Fill History and Order History

### ISSUE THREAD

**Issue by Lavande** [Loopring/dexwebapp#98]
I just found that fees are incorrectly displayed in both Fill History and Order History sections.
The number is ridiculously large. Please check the response from:
https://api.loopring.io/api/v1/user/trades
The value of key "fee" in the JSON data (for SELL orders in my case) is not correct.
![Screenshot from 2020-03-07 13-10-00](https://user-images.githubusercontent.com/2290696/76137292-f53bd280-6075-11ea-9e55-a8ef02c021cd.png)
![Screenshot from 2020-03-07 13-11-13](https://user-images.githubusercontent.com/2290696/76137294-ff5dd100-6075-11ea-920d-4ee7b98c6897.png)

**Comment by dong77** [comment]
The fees are uint256 in json. If the fee is charged in Ether, then 1 ether will be "1" followed by 18 ”0"s.

**Comment by xiaowheat** [comment]
Behave correctly.
