### ISSUE TITLE
whenever cancelling open orders it wont reflect in the UI

### ISSUE THREAD

**Issue by ruhaise** [Loopring/dexwebapp#99]
i think the UI reflect whenever you do a change in open orders

**Comment by dong77** [comment]
I think there is a notification that tells you your order is canceled, and the canceled order moves from open orders to historical orders. Did I miss something, @ruhaise?

**Comment by ruhaise** [comment]
@dong77 recently checked it and looks like the bug is solved, previously the UI was not rerendering, now it's gone as soon as the cancel is pressed,
